    eureka:
     instance:
       prefer-ip-address: true
       client:
         fetch-registry: true
         register-with-eureka: true
         serviceUrl:
           defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
           
     okta:
       oauth2:
         issuer: https://dev-55939633.okta.com/oauth2/default
         audience: api://default
